version: "3.9"
services:
  pihole:
    container_name: pihole
    image: "pihole/pihole"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      TZ: "Europe/Warsaw"
      WEBPASSWORD: "${PI_HOLE_PASSWORD}"
    volumes:
      - "./pihole/etc-pihole:/etc/pihole"
      - "./pihole/etc-dnsmasq.d:/etc/dnsmasq.d"
  homeassistant:
    container_name: homeassistant
    image: "lscr.io/linuxserver/homeassistant:latest"
    network_mode: host
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Warsaw"
    volumes:
      - "./ha/config:/config"
    restart: unless-stopped
